### ISSUE TITLE
Statistics for time period

### ISSUE THREAD

**Issue by mpatas** [NobodyForNothing/blood-pressure-monitor-fl#106]
**What you want**
Perhaps it would be possible to have statistics page show statistics for the same time period for which the data is plotted (the current option would correspond to "Lifetime")?

**Why you want it**
It might be that the data differs at various times, so, it could be informative to compare, let's say, average blood pressure this month and the previous month.

**Comment by NobodyForNothing** [comment]
Yeah the current format corresponds to lifetime. Having the advanced interval selection is already implemented and will come with the next version . So this is a duplicate of #46.
