### ISSUE TITLE
Let the User define horizontal lines in the Graph

### ISSUE THREAD

**Issue by amie42** [NobodyForNothing/blood-pressure-monitor-fl#119]
**What you want**
I would like to mark certain fixed values to be highlighted by horizontal lines in the Graph.

**Why you want it**
My doctor and I defined certain target values to aim for. E.g. 130/80 mmHG so I would like to permanently highlight them in the 
graph

**Comment by uli-on** [comment]
Isn't that the same as the warn values you define in the prefs? These become visible in the graph as soon as your values exceed these.

**Comment by uli-on** [comment]
Strike my last comment, I just read your parallel topic on coloured needle points. That's more complex than I thought.
