### ISSUE TITLE
Unixstamps as date in PDF export

### ISSUE THREAD

**Issue by kri164** [NobodyForNothing/blood-pressure-monitor-fl#131]
How to change unixstamps to normal human date in pdf export?
Thanks

**Comment by NobodyForNothing** [comment]
Just enable custom export fields and drag the normal time format into the list above hidden Fields. You can hide the Unix one by dragging it to the hidden fields.

If you don't mind, I will keep this open as an issue, as Unix timestamps are uncommon for pdf export and should not be the default.

**Comment by kri164** [comment]
Hello,

it helps. Thank you.

I didnt noticed the possibility to move/hide options. There is no listbox side bar.

I suggest to change defaut to normal time.

Thank you very much


22. srpna 2023 17:07:40 UTC, derdilla ***@***.***> napsal:
