### ISSUE TITLE
Problems on the export page, beyond #128

### ISSUE THREAD

**Issue by uli-on** [NobodyForNothing/blood-pressure-monitor-fl#138]
**What happened**
Here's a compact list of issues observed. Should you prefer separate ones, just yell. 

- The "heads up" text is displayed incorrectly even when the defaults aren't changed 
- The OK button does not close this reminder
- There are no custom parameters for CSV export available
- Endless scrollable page footer in light gray, below the headline switch (when CSV is selected) where I've expected the parameter selector

Edited to add tech data:
BPM v1.4.3
Android 10
Fairphone 3
Google Play Services v23.13.12
Webview v111.0.5563.116

**Comment by NobodyForNothing** [comment]
The last 2 should be fixed in v1.4.4, the other ones might also be a consequence of the bug. I would appreciate an update on this, once you get the new version (F-Droid build cycles have been quite slow recently).

Btw: Most of the important app info for bug reporting can be found when tapping on the app version in settings.

**Comment by uli-on** [comment]
> I would appreciate an update on this, once you get the new version

Yes, of course, I 'm so keen on trying out the export functionality that I won't forget to report back. 

> Btw: Most of the important app info for bug reporting can be found when tapping on the app version in settings.

Ah, that's great, but it required patience and a good memory. Do you think it would be possible to tap on the page and have all these information in the clipboard?

**Comment by NobodyForNothing** [comment]
Noticed this issue as well, I will add copy / create bug report buttons later. 
For now I would just make a screenshot.

**Comment by uli-on** [comment]
OK, I've now tried all issues reported here, and all seem fixed. I've yet to find out why the "heads up" text appeared one time without noticeable reason, but I'm not yet versed enough with all these options to be sure. 

But I'm absolutely happy now with the possibility to quickly hand my data over to the My Heart app! Huuuge thanks!! :))

**Comment by uli-on** [comment]
> I've yet to find out why the "heads up" text appeared one time without noticeable reason

It looks like there's two triggers for the heads up check, the bookmark/preset button (though not in both directions, i. e. does not remove an already visible dialogue) as well as the process of opening the ex/import page. Not yet covered seems to be changing the file type.

Also, the  heads up dialogue can't be closed when CSV is selected in combination with the My Heart preset.

(Might find some more, but these are the ones I always came across.)

**Comment by NobodyForNothing** [comment]
Thanks for the investigation, I haven't really changed the conditions after reworking the export system. I will make sure to look into it!
