### ISSUE TITLE
[BUG] - <Unable to import CVS>

### ISSUE THREAD

**Issue by mttrld1989** [NobodyForNothing/blood-pressure-monitor-fl#156]
### Description

As per title, I am unable to import a CVS file. Not just one I modified with new readings, but even one that I just exported from the app. The error is "This can't be imported".

### Android version

Android 13

**Comment by NobodyForNothing** [comment]
Thank you for your bug report. 
I can't reproduce this problem with the default export configuration. Could you provide your export configuration? The quickest way to do so is to click on the version page at the bottom of the settings page and send a screenshot.

**Comment by mttrld1989** [comment]
Dure thing

![Screenshot_20230924-133521](https://github.com/NobodyForNothing/blood-pressure-monitor-fl/assets/51270382/4a689585-be06-4148-8520-de6f2d8a6a7c)

**Comment by NobodyForNothing** [comment]
Thanks for the information. Have you already tried disabling custom export fields?

I just published version 1.5.2, which adds a more helpful error message in case CSV import fails. It would be great to hear about your issue once the version went through the F-Droid build cycle in about a week (I assume you use F-Droid). If you use Google Play, it should be a bit quicker.

**Comment by mttrld1989** [comment]
I have tried yes. And you're correct, I use F-Droid.

I will update this once I have more info from the new version.

**Comment by mttrld1989** [comment]
Hi, just to let you know that I have installed the 1.5.2 version and this problem seems to have solve itself.
