### ISSUE TITLE
Save PF only

### ISSUE THREAD

**Issue by SnejPro** [NobodyForNothing/blood-pressure-monitor-fl#229]
### What you want:

Possibilty to just save the pulse frequency

### Why you want it:

I'd like to save only pulse frequency measurements in the app from time to time, but it is not possible because blood pressure is a mandatory value.

**Comment by NobodyForNothing** [comment]
Does the allow missing values option in the app settings suffice?

**Comment by SnejPro** [comment]
Sorry, I haven't seen this.
