### ISSUE TITLE
[FEATURE] - Save taking of medicine 

### ISSUE THREAD

**Issue by SnejPro** [NobodyForNothing/blood-pressure-monitor-fl#230]
### What you want:

Possibility to save the time and name of taking of medicine

**Comment by NobodyForNothing** [comment]
This also feels like something that is already possible. You can enter a note without entering values.

**Comment by SnejPro** [comment]
Yes, that's possible.
But it would be great, if there is a list from which you can select a specific medicine and maybe if it would be displayed in the graph in some way.
