### ISSUE TITLE
[FEATURE] - Import preview

### ISSUE THREAD

**Issue by NobodyForNothing** [NobodyForNothing/blood-pressure-monitor-fl#241]
### What you want:

Before importing records there could be an additional confirmation that lists the records that will be added.

There could be more interactivity in the import process, for example for the selection of one of multiple csv columns that provide the same data.

### Why you want it:

This can help in cases where the pattern doesn't behave as expected and avoid realizing the mistake later on.

### Progress

- [X] Import preview
- [X] Column selection
- [X] Error feedback
- [x] No headline checkbox
- [ ] ~~Show original column name in dropdown~~
- [ ] Format parsed timestamps and display colors
- [x] Fix todos
- [x] testing

**Comment by alensiljak** [comment]
Seeing a top 10 records would be great.
A checkbox for manually determining if there is a header record or not.
Ability to select and map columns.
Provide feedback to the user about any issues during import.
