### ISSUE TITLE
Prefill on edit doesn't work

### ISSUE THREAD

**Issue by NobodyForNothing** [NobodyForNothing/blood-pressure-monitor-fl#269]
### Description

When opening the edit measurement dialoge through the edit button a normal add measurement dialoge is opened.

### Android version

Android 9, 14

### Reproduction steps

```bash
1. Add measurement
2. tap edit button in list
```

### App debug info

```bash
v1.6.0
```

**Comment by tom-bec** [comment]
thx for adding the bug to the buglist. 
...and sorry, i`ve forgot something: great app!
Greetz Tom
