### ISSUE TITLE
F-Droid Security Warning Version 1.6.3

### ISSUE THREAD

**Issue by T-o-b-i-a-s** [NobodyForNothing/blood-pressure-monitor-fl#306]
### Description

Thanks for the nice and free app. When trying to update the App to 1.6.3 in F-Droid, I get the attached warning message. Could you check that?
![IMG_20240320_070332](https://github.com/NobodyForNothing/blood-pressure-monitor-fl/assets/34947123/6ed9b7b9-f371-4634-98dd-6c05403276bf)

I did not check the commits yet, but did your latest changes include any nstructions that could be considered dangerous by Google Play Protect?

### Android version

Android 12

### Reproduction steps

```bash
With automatic Updates enabled in F-Droid, the app did not update automatically. When trying to update manually, the attached message appears.
```

### Screenshots & Settings backup

```bash
![IMG_20240320_070332](https://github.com/NobodyForNothing/blood-pressure-monitor-fl/assets/34947123/6ed9b7b9-f371-4634-98dd-6c05403276bf)
```

**Comment by pbanj** [comment]
I get the same thing. It would be nice if the warning actually said what the problem was instead of just a generic message

**Comment by rLy07** [comment]
I also got it in the morning when I tried to install it on a new phone. So I installed the older version 1.6.2 but during the day it did auto upgrade itself without any further warning.

**Comment by NobodyForNothing** [comment]
There were no recent changes to how the app behaves on the device and the permissions it consumes.

Play protects complain can originate from the different signing key for F-droid and [Google Play Store](https://play.google.com/store/apps/details?id=com.derdilla.bloodPressureApp) (not sure about why now?). 

You can install the Play version (make sqlitedb backup before) or proceed with the fdroid version.

Unfortunately I don't think this is actionable on my end.

**Comment by pbanj** [comment]
> There were no recent changes to how the app behaves on the device and the permissions it consumes.
> 
> Play protects complain can originate from the different signing key for F-droid and [Google Play Store](https://play.google.com/store/apps/details?id=com.derdilla.bloodPressureApp) (not sure about why now?).
> 
> You can install the Play version (make sqlitedb backup before) or proceed with the fdroid version.
> 
> Unfortunately I don't think this is actionable on my end.

i have apps that have playstore versions and f-droid/github versions and none of them have ever thrown this error. maybe try and contact google and ask them why

**Comment by pbanj** [comment]
fairmail, nova video player, all the "simple" apps ex simple gallery.

**Comment by NobodyForNothing** [comment]
An [appeal](https://developers.google.com/android/play-protect/warning-dev-guidance#request-appeal) has been requested.

That google doesn't provide a more clear message is really strange, as the warning string you reported doesn't show up on their [own list](https://developers.google.com/android/play-protect/warning-strings).

**Comment by pbanj** [comment]
> An [appeal](https://developers.google.com/android/play-protect/warning-dev-guidance#request-appeal) has been requested.
> 
> That google doesn't provide a more clear message is really strange, as the warning string you reported doesn't show up on their [own list](https://developers.google.com/android/play-protect/warning-strings).

i hate when companies do this crap. all it does is scare non tech savvy people and piss tech people off, and cause issues for devs who cant do much because theres nothing to go off of. like how hard is it to include an actual reason. instead of just being like "no it bad". hopefully they dont just brush you off.

**Comment by NobodyForNothing** [comment]
Based on the apk I can't see how Play Protect comes to this conclusion, as common scanning tools like [VirusTotal](https://www.virustotal.com/gui/file/d7f0ff420225aa4687e2abb5cdbc3719e9a840fe028d15cf567982573f2c3edc) report the F-Droid apk as completely fine.

Although if this is a problem with different signing this might be an opportunity to start with F-Droids reproducible builds. Although that would require F-Droid users to delete and reinstall the app.

**Comment by pbanj** [comment]
well you have a way to backup and restore. so having to reinstall wouldnt be that bad. better that than google making you look bad

**Comment by NobodyForNothing** [comment]
I can reproduce this neither on an emulator nor on my device. I don't know if Google actually fixed this or if it's just being selective so it would be great to hear from users whether Play Protect still complains.

**Comment by pbanj** [comment]
Just tried again. No warning this time. So maybe google actually fixed it

**Comment by T-o-b-i-a-s** [comment]
In the meantime F-Droid has automatically updated the app to 1.6.3. with no further confirmation or approval from my side. So it seems the Google Play altert has disappeared. 
I think we can close the issue.
