### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [NobodyForNothing/blood-pressure-monitor-fl#340]
### Description

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7242329933#L796

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/8eb34dcb491fda8fc3aaa69f5029fd74a3e8f44d

**Comment by NobodyForNothing** [comment]
fixed in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15306
