### ISSUE TITLE
Contributing / build instructions?

### ISSUE THREAD

**Issue by pimlie** [NobodyForNothing/blood-pressure-monitor-fl#409]
Would it maybe be possible to add some contributing / local build instructions? I wanted to take a look if I could resolve the issue of my device returning all measurements instead of just the last one, but unfortunately I ran into some issues setting up a local env.  

F.e. after some debugging I realized the health_data_store package is using Freezed so it needs to be build before you can run the app, but even after building I'm getting build errors f.e. due to BloodPressureRecord->time having a default return value of `null` but the factory for BloodPressureRecord specified it has a required DateTime return type. Not sure if that's a bug or that I'm missing some build instruction?

![image](https://github.com/user-attachments/assets/881f49fd-abd0-4d2a-bb4a-5398517b5f71)

Running `dart fix --dry-run` on both the app as the health_data_store lib shows other issues as well.

Also not sure if you use VSCode for developing, but if so do you use the Freezed extension? If so, maybe it can be added as [recommended extension](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions)?

**Comment by NobodyForNothing** [comment]
To build I would follow the steps in the [CI build](https://github.com/NobodyForNothing/blood-pressure-monitor-fl/blob/main/.github/workflows/app-CI.yml#L157-L168). Thanks allot for the feedback, I will add a more in-depth contributor guide.

If you have any more problems feel free to reach out!

**Comment by NobodyForNothing** [comment]
PS: Sorry, I don't use vs-code for flutter, I will try to look into it when writing the guide. In general you don't need to change anything in the health_data_store package.

I don't recognize your build error, may be validate that your files are the ones from the main branch?
