### ISSUE TITLE
"Export after every entry" not working as expected

### ISSUE THREAD

**Issue by JohnVeness** [NobodyForNothing/blood-pressure-monitor-fl#418]
### App version

1.7.3

### Bug Description

If I enable "Export after every entry", the exact same date range is exported each time, rather than (as expected) e.g. the last seven days.

### Steps to Reproduce

1. Go to Settings
2. Export / Import
3. Choose a date range, e.g. 7 days
4. Export after every entry: Enable
5. Export format: PDF (not sure if important, but that's what I'm using)
6. Take some readings over several days
7. Look at PDFs generated

Observed result:
Other than the filename, the PDFs are identical, all showing data from e.g. 1 Aug to 7 Aug.

Expected result:
The first PDF to have data from 1 Aug to 7 Aug, the second PDF to have data from 2 Aug to 8 Aug, etc.

### Details (Screenshots, Debug Info, Configurations)

<details><summary>Attachments</summary>

</details>

**Comment by NobodyForNothing** [comment]
Thanks! The fix will land in 1.8.1.
