### ISSUE TITLE
Support preferred weight unit

### ISSUE THREAD

**Issue by pimlie** [NobodyForNothing/blood-pressure-monitor-fl#435]
### What you want:

Similar to preferred pressure unit, it would be nice if users could indicate a preferred weight unit like `kg`, `lbs` and/or `stone`

### Why you want it:

Because Imperial units still exists even though Metric is much easier :(

**Comment by NobodyForNothing** [comment]
Thanks for the issue [;)](https://github.com/NobodyForNothing/blood-pressure-monitor-fl/blob/9588520ffb0e87f0d4f34756c374679b4e94136b/app/lib/features/measurement_list/weight_list.dart#L39). I didn't even know about the `stone` unit.
