### ISSUE TITLE
record edition

### ISSUE THREAD

**Issue by gargamel17** [NobodyForNothing/blood-pressure-monitor-fl#5]
Hello dear, thank you for creating this app.
How can we edit a record for correction ?
Thanks

**Comment by NobodyForNothing** [comment]
This is indeed an issue. I will add a propper way to do this in the next days.

Right now there is a workaround: you can export the data change the wrong lines (caution when changing the timestamp; you would need to delete the app data) save the file and import it again.

**Comment by NobodyForNothing** [comment]
This will take effect in the next release
