### ISSUE TITLE
Allow Comment only entries / incomplete data

### ISSUE THREAD

**Issue by amie42** [NobodyForNothing/blood-pressure-monitor-fl#75]
Hi, 

I tried to add a comment only entry (just took a note where I took my medication)  sadly that's not possible yet. would be very handy to have though.

Best
Amie

**Comment by NobodyForNothing** [comment]
Thanks for the good idea Amie. I didn't think people would try that, but you proved me wrong. Might add a separate line to the graph and make it appear differently in the list.
