### ISSUE TITLE
Time period for two days

### ISSUE THREAD

**Issue by mpatas** [NobodyForNothing/blood-pressure-monitor-fl#77]
**What you want**

Perhaps it would be worth to add a time period "Two days" or "Day and a day before it" to "Day", "Week", "Month", "Year" and "Lifetime"?

**Why you want it**

With current list of time periods, the graph "Day" becomes rather uninformative when the first data points for new day are entered, the graph "Week" becomes rather uninformative  when the first data points for new week are entered etc. That is, there are not enough points to have a graph that shows some trend. At the moment it looks like the most simple way to handle that is to have an additional option of time period that includes two days (although maybe something like that might also be useful for weeks etc.) - for example, today and yesterday.

**Comment by NobodyForNothing** [comment]
This actually pins down a problem, I never quite realized I had.
I'm going to implement a generic version where you can specify the amount of passed intervalls it shows.

This concept is a bit complicated and I haven't seen it in any apps that show statistics yet (some let you scroll the graph freely, which isn't really feasible for performance reasons here). In case you got a nice way to communicate this setting with the user, feel free suggest it.
