### ISSUE TITLE
Systolic value wraps on smaller screens/larger font sizes

### ISSUE THREAD

**Issue by StarGazer1258** [NobodyForNothing/blood-pressure-monitor-fl#78]
**What happened**
The systolic value on the stats page wraps to two lines on a smaller screen.

On my Samsung Galaxy S22:
![Screenshot_20230701_224918.jpg](https://github.com/NobodyForNothing/blood-pressure-monitor-fl/assets/5743684/e1a391b5-0ab1-4092-804e-3d073f87407a)

**ideas**
May also have to do with font size set on phone. If I decrease font size, it fits fine.

**Comment by NobodyForNothing** [comment]
Rhank you for the bug report, that looks really odd.

How do you think I could fix that / can you suggest a alternate layout? Just ignoring the system settings will annoy someone else.
