### ISSUE TITLE
Remove translation CLA

### ISSUE THREAD

**Issue by comradekingu** [NobodyForNothing/blood-pressure-monitor-fl#88]
It is a barrier to entry, and doesn't do anything beyond posting an announcement.
https://hosted.weblate.org/contributor-agreement/blood-pressure-monitor-fl/app/?next=/projects/blood-pressure-monitor-fl/app/

**Comment by NobodyForNothing** [comment]
seems sensible

**Comment by uli-on** [comment]
Oh, it's Weblate now! Great!
